version: '3'
services:
  facexzoo:
    environment:
        TZ: Asia/Tokyo
    # restart: always
    stdin_open: true
    build: .
    shm_size: '16gb'
    container_name: 'facexzoo'
    working_dir: '/workspace'
    tty: true
    volumes:
      - ~/wf/FaceX-Zoo:/workspace
    image: facexzoo
    deploy:
      resources:
        limits:
          memory: 16gb
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
